### ISSUE TITLE
Gulp + proxy = no injection 

### ISSUE THREAD

**Issue by jessewallace** [BrowserSync/gulp-browser-sync#26]
Hey all,

I have my Gulp task properly preprocessing my files, but it's not injecting the CSS.  It's actually firing a full page reload.

Some background:
- I'm running a Grails app that fires up a localhost:80 server
- We are using Google Maps API and Facebook Auth, so I've set our dev url to forward to localhost:80 in my hosts file (otherwise both APIs give an error because of the domain name)
- When I run Gulp, I'm not getting the notify popups that BrowserSync has loaded
- if i switch proxy to proxy: "mylocaldev.com" to reference my dev url, there is no change
- i've tried the gulp-filter recommendation to make sure only the CSS files are getting hit, but still no change.

I'm using gulp-sass 0.7.2 and browser-sync 1.3.5

``` javascript
var gulp        = require('gulp'),
    browserSync = require('browser-sync'),
    reload      = browserSync.reload,
    sass = require('gulp-sass'),
    path = require('path'),
    minifyCSS = require('gulp-minify-css'),
    autoprefixer = require('gulp-autoprefixer'),
    rename = require("gulp-rename");
    filter = require("gulp-filter");

var config = {
    files: "web-app/css/**/*.scss",
    proxy: "localhost:80"
}

// browser-sync task for starting the server.
gulp.task('browser-sync', function() {
    browserSync(config)
});

// Sass task, will run when any SCSS files change & BrowserSync
// will auto-update browsers

gulp.task('sass', function () {
    return gulp.src('web-app/css/**/*.scss')
    .pipe(sass())
    .pipe(autoprefixer('last 2 version'))
    .pipe(minifyCSS({keepSpecialComments:0}))
    .pipe(rename({suffix: '.min'}))
    .pipe(gulp.dest('web-app/css/'))
    .pipe(filter('web-app/css/**/*.css'))
    .pipe(reload({stream:true}));
});

// Default task to be run with `gulp`
gulp.task('default', ['sass','browser-sync'], function () {
    gulp.watch("web-app/css/**/*.scss", ['sass']);
});
```

Thanks for any help on this, guys.  I'm a UI/UX guy by trade, and this is pretty outside of my realm of comfort :)

**Comment by malfborger** [comment]
@sogko i'm using your config bu im only recieving following in ther terminal 
```➜  wp git:(master) ✗ gulp default```
```[11:11:28] Using gulpfile ~/Sites/garbergs.se/wp/gulpfile.js```
```[11:11:28] Starting 'sass'...```
```[11:11:28] Starting 'browser-sync'...```
```[11:11:28] Finished 'browser-sync' after 22 ms```
```[BS] Proxying: http://localhost:9001```
```[BS] Now you can access your site through the following addresses:```
```[BS] Local URL: http://localhost:3000```
```[BS] External URL: http://10.15.2.155:3000```
```[BS] Watching files...```
```[11:11:28] Finished 'sass' after 480 ms```
```[11:11:28] Starting 'default'...```
```[11:11:28] Finished 'default' after 17 ms```
```[BS] File changed: wp-content/themes/garbergs-theme/styles/component.css```

it doesn't say " [BS] Injecting file into all connected browsers... "

**Comment by ocombe** [comment]
So I had the same problem: browser sync was doing a full reload because the sourcemap files changed at the same time as the css files. I filtered the *.map files and it injects the css without full reload now.

**Comment by makbeta** [comment]
Having the same issue. 
Found out that the loaded page, browsersync automatically insert the following JS code

`<script type='text/javascript' id="__bs_script__">//<![CDATA[
    document.write("<script async src='/browser-sync/browser-sync-client.2.8.2.js'><\/script>".replace("HOST", location.hostname));
//]]></script>`

For me this snippet fails because my html also has <base> tag in it, so it attempts to load the js file from the external, rather than local server. 

I believe the auto-generated snippet should be updated to the following for it to work correctly across all configurations.

`<script type='text/javascript' id="__bs_script__">//<![CDATA[
    document.write("<script async src='http://HOST/browser-sync/browser-sync-client.2.8.2.js'><\/script>".replace("HOST", location.hostname));
//]]></script>`

**Comment by tatemz** [comment]
Per @ocombe - My problem was also an issue with `*.map` files being included in the pipe.

**Comment by hkirsman** [comment]
Can't get this working. Tried all the different code examples. Best I get this page reload.

**Comment by hkirsman** [comment]
Oh well it seems that BrowserSync does not support @import and that's what Drupal is using if aggregation is not enabled. Here's the issue and fix: https://github.com/BrowserSync/browser-sync/issues/534

**Comment by zirho** [comment]
anyone who struggle with map file injection causing full reload 
try something like this
```
gulp
.src('./public/css/*.css')
.pipe(browserSync.stream({match: '**/*.css'}));
```
this injects only css file to it so no full refresh with this

**Comment by martinesdevelop** [comment]
zirho, thanks! It helps me!

**Comment by riggerthegeek** [comment]
I've had a similar problem, although the cause is (perhaps) different. I'm putting this here as this is the top link when I search for "browsersync not injecting css" in the hope it's helpful to others.

My gulpfile is using the [connect-modrewrite](https://www.npmjs.com/package/connect-modrewrite) to rewrite links - it ensures that all URLs are routed through the index.html file (important for Angular).  It appears that, when injecting the compiled CSS in, it's routing the CSS through the index.html file. The browser doesn't do this, so it's not immediately apparent there's a problem.  See task below:

```javascript
var modRewrite = require("connect-modrewrite");
gulp.task("default", ["clean", "bundle", "templates:watch", "sass"], function () {

    browserSync.init({
        open: false,
        server: {
            baseDir: "./src",
            middleware: [
                modRewrite([
                    "^\/assets/(.*) /assets/$1 [L]",
                    "!\\.\\w+$ /index.html [L]"
                ])
            ]
        }
    });

    gulp.watch(src.sass, ["sass"]);
    gulp.watch(src.html, ["templates:watch"])
        .on("change", reload);

});
```

By adding `"^\/assets/(.*) /assets/$1 [L]",` to the modRewrite array, it ensures my compiled CSS is injected correctly.

**Comment by jobayerarman** [comment]
Adding 
```js 
.on("change", reload) 
``` 
fixed my issus.

```js
gulp.task( 'watch', ['browser-sync'], function() {
  gulp.watch( watch.styles, [ 'styles' ] );
  gulp.watch( watch.html, [ 'render-html' ] ).on("change", reload );
  gulp.watch( watch.scripts, [ 'scripts' ] ).on("change", reload );
});
```

**Comment by Onotoley** [comment]
I've done all things I could ever find and for me it still doesn't work:
- I've added the browsersync module to drupal, enabled it in my theme,
- Set up with proxy in gulpfile of my local website url

I getting new tab opened with a pop-up saying "Connected to browsersync" but still on any style change I don't get any reload or anything.

**Comment by Vaggos** [comment]
@Onotoley for a Drupal setup you can find a lot of info here [Switch current omega sub-theme to LibSass](https://www.drupal.org/node/2537364). No need for any Drupal module. I have provided step to step instruction on #20 comment. Plus a lot of info by other guys.

**Comment by demisx** [comment]
Same here. No longer works, though the browser shows "Injected" message. Have to hit reload each time to see the changes. Using the latest BS 2.18.8.

**Comment by ocombe** [comment]
I no longer maintain this project (I use webpack now) and it's probably in a bad shape. If someone wants to take over, let me know
